class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'id': {
      'cover_headline': 'Fokus Upgrade Diri\nTanpa Distraksi.',
      'cover_subtitle':
          'Fokuskan upgrade diri tanpa ribet iklan atau subscribe. Simpan kutipan berharga, catat refleksi personal, dan bangun perpustakaan pengetahuan privat.',
      'cover_badge': 'Bebas Iklan · Tanpa Langganan · 100% Offline 🛡️',
      'slide_to_enter': 'Geser panah untuk masuk',
      'created_by': 'Created by smugh-tech',
      'profile_title': 'Profil Saya',
      'reading_target': 'Target Membaca',
      'target_summary': '12 buku tahun ini',
      'reading_stats': 'Statistik Membaca',
      'appearance_settings': 'Pengaturan Tampilan',
      'appearance_subtitle': 'Ubah foto profil & cover depan',
      'sync_and_backup': 'Sinkronisasi & Backup',
      'export_notes': 'Ekspor Catatan',
      'language': 'Bahasa / Language',
      'about': 'Tentang Book&Mind',
      'logout': 'Keluar dari Akun',
      'under_development': 'Under Development',
      'sync_dev_title': 'Sinkronisasi & Backup Cloud',
      'sync_dev_desc':
          'Fitur pencadangan cloud dan sinkronisasi otomatis antar perangkat sedang dalam tahap pengembangan aktif oleh tim smugh-tech.\n\nSaat ini seluruh buku, progres membaca, catatan, dan highlight tersimpan 100% aman di database SQLite lokal perangkat Anda.',
      'understood': 'Mengerti',
      'appearance_title': 'Pengaturan Tampilan',
      'profile_photo_section': 'Foto Profil Pengguna',
      'profile_photo_desc':
          'Pilih foto dari galeri/berkas atau gunakan avatar inisial bawaan.',
      'change_profile_photo': 'Ganti Foto Profil',
      'cover_photo_section': 'Foto Cover Depan',
      'cover_photo_desc':
          'Pilih gambar latar belakang layar cover depan aplikasi.',
      'change_cover_photo': 'Ganti Foto Cover',
      'reset_to_default': 'Kembalikan ke Default',
      'original_app_default': 'Gambar bawaan aktif (Original)',
      'custom_photo_active': 'Foto kustom aktif',
      'export_title': 'Ekspor Catatan & Refleksi',
      'export_desc':
          'Unduh atau salin seluruh catatan dan kutipan berharga ke format Markdown (.md) atau Teks (.txt).',
      'export_markdown': 'Ekspor ke Markdown (.md)',
      'export_markdown_desc': 'Format rapi untuk Obsidian, Notion, Logseq',
      'export_txt': 'Ekspor ke Teks (.txt)',
      'export_txt_desc': 'Format teks polos sederhana untuk dibaca langsung',
      'copy_clipboard': 'Salin Catatan ke Clipboard',
      'save_to_file': 'Simpan Berkas ke Perangkat',
      'export_empty': 'Belum ada catatan atau refleksi untuk diekspor.',
      'export_success': 'Berkas berhasil disimpan ke:',
      'copy_success': 'Seluruh catatan berhasil disalin ke papan klip!',
      'select_language': 'Pilih Bahasa Aplikasi',
      'lang_id': 'Bahasa Indonesia',
      'lang_en': 'English',
      'close': 'Tutup',
      'motivation_header': 'MOTIVASI MEMBACA',
      'quote_1': 'Jadikan membaca jendela untuk bertumbuh setiap hari. Satu halaman kecil membuka cakrawala tak terbatas.',
      'quote_tag_1': 'Inspirasi Bertumbuh',
      'quote_2': 'Membaca bukan sekadar menghabiskan buku, melainkan membiarkan buku memperluas caramu berpikir dan menjalani hidup.',
      'quote_tag_2': 'Refleksi Diri',
      'quote_3': 'Buku adalah percakapan paling tenang dengan pikiran-pikiran terhebat sepanjang masa. Buka lembarannya, temukan dirimu.',
      'quote_tag_3': 'Sahabat Pikiran',
      'quote_4': 'Luangkan 15 menit hari ini bersama buku. Jadikan membaca napas bagi jiwa dan investasi abadi bagi masa depanmu.',
      'quote_tag_4': 'Kebiasaan Hidup',
      'quote_5': 'Setiap kutipan yang kau simpan dan renungkan adalah benih kebijaksanaan yang membentuk versi terbaik dari dirimu.',
      'quote_tag_5': 'Jejak Pengetahuan',
    },
    'en': {
      'cover_headline': 'Focus Self-Upgrade\nWithout Distractions.',
      'cover_subtitle':
          'Focus on self-upgrade without annoying ads or subscriptions. Save valuable quotes, reflect personally, and build a private knowledge hub.',
      'cover_badge': 'Ad-Free · No Subscription · 100% Offline 🛡️',
      'slide_to_enter': 'Swipe arrow to enter',
      'created_by': 'Created by smugh-tech',
      'profile_title': 'My Profile',
      'reading_target': 'Reading Target',
      'target_summary': '12 books this year',
      'reading_stats': 'Reading Statistics',
      'appearance_settings': 'Appearance Settings',
      'appearance_subtitle': 'Customize profile & cover photo',
      'sync_and_backup': 'Sync & Backup',
      'export_notes': 'Export Notes',
      'language': 'Language / Bahasa',
      'about': 'About Book&Mind',
      'logout': 'Log Out',
      'under_development': 'Under Development',
      'sync_dev_title': 'Cloud Sync & Backup',
      'sync_dev_desc':
          'Cloud backup and cross-device sync features are currently under active development by the smugh-tech team.\n\nAll your books, reading progress, notes, and highlights remain 100% safe inside the local offline SQLite database on your device.',
      'understood': 'Understood',
      'appearance_title': 'Appearance Settings',
      'profile_photo_section': 'User Profile Photo',
      'profile_photo_desc':
          'Select a photo from your gallery/files or use the default initials avatar.',
      'change_profile_photo': 'Change Profile Photo',
      'cover_photo_section': 'Cover Screen Image',
      'cover_photo_desc':
          'Select the background image displayed on the app cover screen.',
      'change_cover_photo': 'Change Cover Image',
      'reset_to_default': 'Reset to Default',
      'original_app_default': 'Original default image active',
      'custom_photo_active': 'Custom photo active',
      'export_title': 'Export Notes & Reflections',
      'export_desc':
          'Download or copy all valuable notes and quotes to Markdown (.md) or Plain Text (.txt) formats.',
      'export_markdown': 'Export to Markdown (.md)',
      'export_markdown_desc': 'Structured format for Obsidian, Notion, Logseq',
      'export_txt': 'Export to Plain Text (.txt)',
      'export_txt_desc': 'Simple plain text format for direct reading',
      'copy_clipboard': 'Copy Notes to Clipboard',
      'save_to_file': 'Save File to Device',
      'export_empty': 'No notes or reflections found to export yet.',
      'export_success': 'File successfully saved to:',
      'copy_success': 'All notes successfully copied to clipboard!',
      'select_language': 'Select App Language',
      'lang_id': 'Bahasa Indonesia',
      'lang_en': 'English',
      'close': 'Close',
      'motivation_header': 'READING MOTIVATION',
      'quote_1': 'Make reading a window for daily growth. One small page opens boundless horizons.',
      'quote_tag_1': 'Growth Inspiration',
      'quote_2': 'Reading is not merely about finishing books, but allowing books to expand how you think and live.',
      'quote_tag_2': 'Mindful Reflection',
      'quote_3': 'A book is a quiet conversation with the greatest minds in history. Open its pages and find yourself.',
      'quote_tag_3': 'Companion of the Mind',
      'quote_4': 'Dedicate 15 minutes today with a book. Make reading breath for your soul and a lifelong habit.',
      'quote_tag_4': 'Daily Habit',
      'quote_5': 'Every quote you save and reflect upon is a seed of wisdom shaping the best version of who you are.',
      'quote_tag_5': 'Knowledge Journey',
    },
  };

  static String tr(String key, String lang) {
    return _strings[lang]?[key] ?? _strings['id']?[key] ?? key;
  }

  static List<Map<String, String>> getMotivationalQuotes(String lang) {
    return [
      {
        'quote': tr('quote_1', lang),
        'tag': tr('quote_tag_1', lang),
      },
      {
        'quote': tr('quote_2', lang),
        'tag': tr('quote_tag_2', lang),
      },
      {
        'quote': tr('quote_3', lang),
        'tag': tr('quote_tag_3', lang),
      },
      {
        'quote': tr('quote_4', lang),
        'tag': tr('quote_tag_4', lang),
      },
      {
        'quote': tr('quote_5', lang),
        'tag': tr('quote_tag_5', lang),
      },
    ];
  }
}
